name: adhara_example
description: Base framework for Flutter Apps with intense networking and data interactivity
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adhara:
    git:
      url: https://github.com/infitio/flutter-adhara.git
      ref: redesign
#    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/resources.properties
    - assets/i18n/resources_hi.properties
    - assets/i18n/resources_te.properties
    - assets/i18n/resources_es.properties
