name: adhara_example
description: Base framework for Flutter Apps with intense networking and data interactivity
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adhara:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/resources.properties
    - assets/i18n/resources_hi.properties
    - assets/i18n/resources_te.properties
    - assets/i18n/resources_es.properties
