name: adhara
description: Base framework for Flutter Apps with intense networking and data interactivity
version: 1.0.3-beta.4
homepage: https://github.com/infitio/flutter-adhara

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  yaml: ^2.2.1

#  built_value: ^6.7.0

  # The following dependency helps to make network calls
  http: ^0.12.1

  # The following dependency is to interact with SQLite database available on mobile
  sqflite: ^1.3.1

  # The following dependency is to interact with Shared Preferences on android and NSUserDefaults on iOS
  shared_preferences: ^0.5.8

  # Plugin for finding commonly used locations on the filesystem.
  path_provider: ^1.6.11

  # cross-platform path manipulation library for Dart
  path: ^1.7.0

  # plugin for launching a URL in browser
  url_launcher: ^5.5.0

  # Error Reporting service
  sentry: ^3.0.1

  # CLI arg parser
  args: ^1.6.0

  chopper: ^3.0.3


executables:
  adhara: adhara


#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  handlebars2: ^0.0.3

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
#flutter:
#
# For details regarding fonts in packages, see
# https://flutter.io/custom-fonts/#from-packages
