name: adhara
description: Base framework for Flutter Apps with intense networking and data interactivity
version: 0.3.6
author: Rohit R. Abbadi <rohit@infitio.com>
homepage: https://github.com/infitio/flutter-adhara

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following dependency helps to make network calls
  http: ^0.12.0+2

  # The following dependency is to interact with SQLite database available on mobile
  sqflite: ^1.1.7+1

  # The following dependency is to interact with Shared Preferences on android and NSUserDefaults on iOS
  shared_preferences: ^0.5.4

  # Plugin for finding commonly used locations on the filesystem.
  path_provider: ^1.4.0

  # cross-platform path manipulation library for Dart
  path: ^1.6.4

  # plugin for launching a URL in browser
  url_launcher: ^5.2.3

  # Error Reporting service
  sentry: ^2.3.1


#dev_dependencies:
#  flutter_test:
#    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
#flutter:
#
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
