name: adhara_example
description: Base framework for Flutter Apps with intense networking and data interactivity
author: Rohit R. Abbadi <rohit@infitio.com>
homepage: https://github.com/infitio/flutter-adhara

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  adhara:
    path: ../
