targets:
  $default:
    builders:
      adhara_generator|adhara:
        enabled: true
        generate_for:
          - '**.model.dart'

builders:
  adhara:
#    target: ":adhara_generator"
    import: "package:adhara_generator/builder.dart"
    builder_factories: ["modelFactory"]
    build_extensions: {".dart": [".adhara.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
