name: adhara_generator
description: Code generator for Flutter-Adhara
version: 0.0.1
author: Rohit R. Abbadi
homepage: https://github.com/infitio/flutter-adhara

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
#  build: '>=0.12.0 <2.0.0'
  build: ^1.0.0
  build_config: '>=0.3.1 <0.5.0'
  analyzer: '>=0.34.0 <0.39.0'
  analyzer_plugin: '>=0.1.0 <0.3.0'
  source_gen: ^0.9.0
  adhara:
    path: ../adhara/

dev_dependencies:
  build_test: ^0.10.9+1
  build_runner: '>=1.2.1 <=1.7.2'
