name: adhara_generator
description: Code generator for Flutter-Adhara
version: 0.0.1
author: Rohit R. Abbadi
homepage: https://github.com/infitio/flutter-adhara

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  build: '>=1.2.1 <2.0.0'
  source_gen: ^0.9.4+6
  adhara:
    path: ../adhara/

dev_dependencies:
  build_test: ^0.10.9+1
  build_runner: '>=1.2.1 <=1.7.2'
  test: ^1.9.4
