name: adhara_generator
description: Code generator for Flutter-Adhara
version: 0.0.1
author: Rohit R. Abbadi
homepage: https://github.com/infitio/flutter-adhara

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  build: '>=1.2.1 <2.0.0'
  adhara:
    path: ../adhara/

dev_dependencies:
  source_gen: ^0.9.6
  analyzer:  ^0.39.13
  build_test: ^1.2.0
  build_runner: ^1.10.0
  test: ^1.15.2
